// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace 宏碁班專案_社交媒體平台MVC.Models;

public partial class Comments
{
    public int ComentId { get; set; }

    public int PostId { get; set; }

    public int UserId { get; set; }

    public string Content { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public int? ParenCommentId { get; set; }

    public virtual ICollection<CommentFavorites> CommentFavorites { get; set; } = new List<CommentFavorites>();

    public virtual ICollection<CommentShares> CommentShares { get; set; } = new List<CommentShares>();

    public virtual ICollection<Comments> InverseParenComment { get; set; } = new List<Comments>();

    public virtual Comments ParenComment { get; set; }

    public virtual Posts Post { get; set; }

    public virtual userInfo User { get; set; }
}