// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace 宏碁班專案_社交媒體平台MVC.Models;



public partial class FriendShip
{
    public int Id { get; set; }

    public int UserId1 { get; set; }

    public int UserId2 { get; set; }

    public FriendshipStatus Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual userInfo UserId1Navigation { get; set; }

    public virtual userInfo UserId2Navigation { get; set; }
}